# Generated by Django 4.2.7 on 2024-02-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='registered_users_count',
            new_name='users_count',
        ),
    ]
