# Generated by Django 4.2.7 on 2024-02-05 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0002_rename_registered_users_count_sitesettings_users_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='users_count',
            new_name='registered_users_count',
        ),
    ]
