# Generated by Django 4.2.7 on 2024-01-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_basket_basketitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
