# Generated by Django 4.2.7 on 2024-02-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_store'),
    ]

    operations = [
    ]
